[tools]
bat = "latest"
bun = "latest"
colima = "latest"
docker-compose = "latest"
fd = "latest"
fnox = "latest"
fzf = "latest"
lazydocker = "latest"
lazygit = "latest"
lima = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
